query getHeroMedia($id: String, $media: String) {
  movieInfo(id: $id, media: $media) {
    id
    title
    media
    backdropPath {
      large
    }
    production_companies
    vote_average
    genres
    runtime
    videos {
      embed
      posterImage
      url
      key
      name
    }
  }
}
