query movieInfo($id: String, $media: String) {
  movieInfo(id: $id, media: $media) {
    id
    title
    media
    backdropPath {
      large
      small
    }
    posterPath {
      large
      small
    }
    overview
    production_companies
    vote_average
    genres
    runtime
    reviews {
      id
      content
      author
    }
    credits {
      id
      name
      profilePath
      character
    }
    videos {
      embed
      posterImage
      url
      key
      name
    }
  }
}
